const site_definition = {
    header:{
        title:"[TITLE]",
        topbar:"[TOPBAR TITLE]",
    },
    landing:{
        include:true,
        title:"[SECTION TITLE TEXT]",
        content:"",
        image:""
    },
    about:{
        include:true,
        text:`Hello! I'm [NAME], a software engineer based in [CITY]. Since graduating from [COLLEGE/UNIVERSITY] in [YEAR], I've been passionate about leveraging technology to solve complex problems.

In my current role at [CURRENT JOB], I develop user-friendly software solutions, helping businesses improve their efficiency and drive innovation. I'm skilled in several programming languages, including Python, Java, and C++.
        
Outside of work, I'm an avid reader and tech enthusiast who loves exploring the latest industry trends. I also enjoy hiking and spending quality time with my family and my dog, Luna.
        
This website is a window into my world, showcasing my projects, my thoughts on tech trends, and some snippets of my personal life. Feel free to explore and reach out if you'd like to connect!
        `,
        image:"",
    },
    work:{
        include:true,
        title:"[SECTION TITLE TEXT]",
        animation: "pullUpDown",
        posts:[
            {
                title:"Electronic Music Playlist",
                type:"tag1",
                subtype:"tag1_subtag1",
                description:"",
                content:"",
                date:"",
                image:"",
                license:"",
                sharing:"",
            },
            {
                title:"Blog 1",
                type:"tag2",
                subtype:"",
                description:"",
                content:"",
                date:"",
                image:"",
                license:"",
                sharing:"",
            },
            {
                title:"Blog 2",
                type:"tag2",
                subtype:"",
                description:"",
                content:"",
                date:"",
                image:"",
                license:"",
                sharing:"",
            },
            {
                title:"Classical Music Playlist",
                type:"tag3",
                subtype:"tag3_subtag1",
                description:"",
                content:"",
                date:"",
                image:"",
                license:"",
                sharing:"",
            },
            {
                title:"Blog 3",
                type:"blog1",
                subtype:"",
                description:"",
                content:"",
                date:"",
                image:"",
                license:"",
                sharing:"",
            },
            {
                title:"Blog 4",
                type:"blog2",
                subtype:"tech",
                description:"",
                content:"",
                date:"",
                image:"",
                license:"",
                sharing:"",
            },
            {
                title:"Blog 5",
                type:"blog2",
                subtype:"tech",
                description:"",
                content:"",
                date:"",
                image:"",
                license:"",
                sharing:"",
            },
            {
                title:"Blog 6",
                type:"blog2",
                subtype:"science",
                description:"",
                content:"",
                date:"",
                image:"",
                license:"",
                sharing:"",
            },
        ]
    },
    contact:{
        include:true,
        email_hash:"dGVzdEB0ZXN0LmNvbQ==",
        artstation:"[ARTSTATION]",
        bandcamp:"[BANDCAMP]",
        codepen:"[CODEPEN",
        deviantart:"[DEVIANT ART",
        discord:"[DISCORD]",
        dribbble:"[DRIBBBLE]",
        ello:"[ELLO]",
        envato:"[ENVATO]",
        facebook:"[FACEBOOK]",
        flickr:"[FLICKR]",
        github:"[GITHUB]",
        hackadayio:"[HACKADAYIO]",
        instagram:"[INSTAGRAM]",
        lastfm:"[LASTFM]",
        linkedin:"[LINKEDIN]",
        mastodon:"[MASTODON]",
        pinterest:"[PINTEREST]",
        reddit:"[REDDIT]",
        reverbnation:"[REVERBNATION]",
        sourceforge:"[SOURCEFORGE]",
        soundcloud:"[SOUNDCLOUD]",
        spacehey:"[SPACEHEY]",
        stackoverflow:"[STACKOVERFLOW]",
        steam:"[STEAM]",
        tiktok:"[TIKTOK]",
        tumblr:"[TUMBLR]",
        twitch:"[TWITCH]",
        twitter:"[TWITTER]",
        turbosquid:"[TURBOSQUID]",
        unity:"[UNITY]",
        unreal:"[UNREAL]",
        vimeo:"[VIMEO]",
        wikipedia:"[WIKIPEDIA]",
        youtube:"[YOUTUBE]"
    }
}

//TEMPALTE rev 2
// var post_## = {post_type:"visuals, audio, science, blog, downloads",
//                post_subtype:"visuals(archviz, graphics, photography, colorizations, motion), audio(electronic, theatrical, samples, sound effects), science(interactives, furniture, software, hardware, research)",
//                post_title:"",
//                post_description:"",
//                post_date:"",
//                post_image:"",
//------------------------------------------------------------------------
//                modal_title:"",
//                modal_summary:"",
//------------------------------------------------------------------------
//                file_struct:"file_name",
//                image_preview:"",
//                image_preview_download:"",
//                paragraph:"This is some demo text to test the JSON parsing functionality when used in the setting of a blog. If this works, it will make developing a blog entry tool very easy.",
//                specifications:"",
//                specifications_elements:"",
//                specifications_process:"",
//                specifications_software:"",
//                specifications_duration:"",
//                interactives:"",
//                image_gallery:"",
//                image_gallery_download:"",
//                image_compare_slide:"",
//                image_compare_fade:"",
//                print_request:"",
//                music_request:"",
//                exhibit_request:"",
//                furniture_request:"",
//                software_request:"",
//                software_download:"",
//                hardware_request:"",
//                share:"y",
//                license:"CC CC-C MIT CR "
//               }   